name: flutter_neumorphic
description: A complete, ready to use, Neumorphic ui kit for Flutter. Dark theming compatible & fully customizable.
version: 3.2.0
#authors: [
#  Florent Champigny <champigny.florent@gmail.com>,
#  Olivier Bonvila <olivier.bonvila@idean.com>,
#  Gyl Jean Lambert <almighty972@gmail.com>
#]
homepage: https://github.com/Idean/Flutter-Neumorphic
issue_tracker: https://github.com/Idean/Flutter-Neumorphic/issues

environment:
  sdk: ">=3.0.0 <4.0.0" # Updated for Flutter 3.10+ compatibility
  flutter: ">=3.10.0" # Minimum Flutter version for 3.10+ features

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Added modern linting rules

flutter:
  fonts:
    - family: NeumorphicIcons
      fonts:
        - asset: fonts/NeumorphicIcons.ttf
